src/Kofti.Manager/Models/AppModel.cs
using System;

namespace Kofti.Manager.Models
{
    public class AppModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime CreatedAt { get; set; }
        public bool IsActive { get; set; }
    }
}

src/Kofti.Manager/Models/ConfigModel.cs
using System;

namespace Kofti.Manager.Models
{
    public class ConfigModel
    {
        public int Id { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
        public DateTime CreatedAt { get; set; }
        public bool IsActive { get; set; }
        public int ApplicationId { get; set; }
    }
}

src/Kofti.Manager/Models/ErrorViewModel.cs
namespace Kofti.Manager.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Kofti.Manager/Controllers/AppsController.cs
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Kofti.Manager.Data;
using Kofti.Manager.Data.Entities;
using Kofti.Manager.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Kofti.Manager.Controllers
{
    [Route("/apps")]
    public class AppsController : Controller
    {
        private readonly KoftiDbContext _dbContext;
        private readonly IMapper _mapper;
        public AppsController(KoftiDbContext dbContext, IMapper mapper)
        {
            _dbContext = dbContext;
            _mapper = mapper;
        }

        // GET
        [HttpGet("")]
        public async Task<IActionResult> Index()
        {
            var apps = await _dbContext.Applications.Where(x => x.IsActive && !x.IsDeleted).ToListAsync();
            return View(apps.Select(x => _mapper.Map<ApplicationEntity, AppModel>(x)).ToList());
        }

        [HttpGet("create")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost("create")]
        public async Task<IActionResult> Create(AppModel app)
        {
            var entity = _mapper.Map<AppModel, ApplicationEntity>(app);
            await _dbContext.Applications.AddAsync(entity);

            try
            {
                await _dbContext.SaveChangesAsync();
            }
            catch
            {
                return View(app);
            }

            return RedirectToAction("Index");
        }


        [HttpDelete("delete/{id}")]
        public async Task<IActionResult> Delete(int appId)
        {
            var entity = await _dbContext.Applications.FindAsync(appId);

            if (entity == null)
            {
                return RedirectToAction("Index");
            }

            _dbContext.Applications.Remove(entity);

            try
            {
                await _dbContext.SaveChangesAsync();
            }
            catch
            {
                // ignored
            }

            return RedirectToAction("Index");
        }
    }
}

src/Kofti.Manager/Controllers/ConfigsController.cs
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Kofti.Manager.Data;
using Kofti.Manager.Data.Entities;
using Kofti.Manager.Models;
using Kofti.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Kofti.Manager.Controllers
{
    [Route("configs/{appId}")]
    public class ConfigsController : Controller
    {
        private readonly KoftiDbContext _dbContext;
        private readonly IMapper _mapper;
        private readonly IConfigService _configService;

        public ConfigsController(KoftiDbContext dbContext, IMapper mapper, IConfigService configService)
        {
            _dbContext = dbContext;
            _mapper = mapper;
            _configService = configService;
        }

        [HttpGet("")]
        public async Task<IActionResult> Index(int appId)
        {
            ViewBag.AppId = appId;
            var configs = await _dbContext.Configs
                .Where(x => !x.IsDeleted
                            && x.ApplicationId == appId)
                .ToListAsync();

            return View(configs.Select(x => _mapper.Map<ConfigEnttiy, ConfigModel>(x)).ToList());
        }

        [HttpGet("create")]
        public IActionResult Create(int appId)
        {
            ViewBag.AppId = appId;
            return View();
        }

        [HttpPost("create")]
        public async Task<IActionResult> Create(int appId, ConfigModel model)
        {
            bool isExists = await _dbContext.Configs.AnyAsync(x => x.Key == model.Key && x.ApplicationId == appId);
            if (isExists)
            {
                return RedirectToAction("Index", new
                {
                    appId
                });
            }

            var entity = _mapper.Map<ConfigModel, ConfigEnttiy>(model);
            entity.ApplicationId = appId;
            await _dbContext.Configs.AddAsync(entity);

            try
            {
                await _dbContext.SaveChangesAsync();
                await ReloadConfig(appId);
            }
            catch
            {
                return View(model);
            }

            return RedirectToAction("Index", new
            {
                appId
            });
        }

        [HttpGet("update/{configId}")]
        public async Task<IActionResult> Update(int appId, int configId)
        {
            var configEntity =
                await _dbContext.Configs.SingleOrDefaultAsync(x =>
                    x.Id == configId && x.ApplicationId == appId && !x.IsDeleted);

            if (configEntity == null)
            {
                return RedirectToAction("Index", new
                {
                    appId
                });
            }

            ViewBag.AppId = appId;

            return View(_mapper.Map<ConfigEnttiy, ConfigModel>(configEntity));
        }

        [HttpPost("update/{configId}")]
        public async Task<IActionResult> Update(int appId, int configId, ConfigModel model)
        {
            var configEntity =
                await _dbContext.Configs.SingleOrDefaultAsync(x =>
                    x.Id == configId && x.ApplicationId == appId && !x.IsDeleted);

            if (configEntity == null)
            {
                return RedirectToAction("Index");
            }

            configEntity.Value = model.Value;
            configEntity.IsActive = model.IsActive;

            _dbContext.Configs.Update(configEntity);

            try
            {
                await _dbContext.SaveChangesAsync();

                await ReloadConfig(appId);
            }
            catch
            {
                return View(model);
            }

            return RedirectToAction("Index", new
            {
                appId
            });
        }

        public IActionResult Delete()
        {
            throw new System.NotImplementedException();
        }

        async Task ReloadConfig(int appId)
        {
            var app = await _dbContext.Applications.Include(x => x.Configs)
                .SingleOrDefaultAsync(x => x.Id == appId);

            await _configService.PublishAsync(app.Name,
                app.Configs.ToDictionary(x => x.Key, x => (object) x.Value));
        }
    }
}

src/Kofti.Manager/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Kofti.Manager.Models;

namespace Kofti.Manager.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

src/Kofti.Manager/Pages/Apps/Create.cshtml
@model AppModel

@{
    ViewBag.Title = "Create App";
    Layout = "_Layout";
}

<h2>Create App</h2>

<form asp-controller="Apps" asp-action="Create" method="post">
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label asp-for="Name">Application Name</label>
        <input asp-for="Name" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

src/Kofti.Manager/Pages/Apps/Delete.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>title</h2>

src/Kofti.Manager/Pages/Apps/Index.cshtml
@model List<Kofti.Manager.Models.AppModel>

@{
    ViewBag.Title = "Apps";
    Layout = "_Layout";
}

<h2>Apps</h2>

@if (Model != null)
{
    <table>
        <thead>
        <tr>
            <td>Id</td>
            <td>Name</td>
            <td>Creation Time</td>
            <td>More</td>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.CreatedAt.ToShortDateString()</td>
                <td>
                    <a asp-action="Index" asp-controller="Configs" asp-route-appId="@item.Id">Show Configs</a>
                </td>
            </tr>
        }
        </tbody>
    </table>
}

src/Kofti.Manager/Pages/Apps/Update.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>title</h2>

src/Kofti.Manager/Pages/Configs/Create.cshtml
@model ConfigModel

@{
    ViewBag.Title = "Create Config";
    Layout = "_Layout";
}

<h2>Create Config</h2>

<form asp-controller="Configs" asp-action="Create" asp-route-appId="@ViewBag.AppId" method="post">
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label asp-for="Key">Key</label>
        <input asp-for="Key" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Value">Value</label>
        <input asp-for="Value" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="IsActive">Is Active</label>
        <input asp-for="IsActive" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

src/Kofti.Manager/Pages/Configs/Index.cshtml
@model List<ConfigModel>

@{
    ViewBag.Title = "Configs";
    Layout = "_Layout";
}

<h2>Configs</h2>
<p>
    <a asp-action="Create" asp-route-appId="@ViewBag.AppId">Create New Config</a>
</p>

@if (Model != null)
{
    <table>
        <thead>
        <tr>
            <td>Id</td>
            <td>Key</td>
            <td>Value</td>
            <td>Is Active</td>
            <td>Creation Time</td>
            <td>More</td>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Key</td>
                <td>@item.Value</td>
                <td>@item.IsActive</td>
                <td>@item.CreatedAt.ToShortDateString()</td>
                <td>
                    <a asp-action="Update" asp-route-appId="@item.ApplicationId" asp-route-configId="@item.Id">Update</a>
                    <a asp-action="Delete" asp-route-appId="@item.ApplicationId" asp-route-configId="@item.Id">Delete</a>
                </td>
            </tr>
        }
        </tbody>
    </table>
}

src/Kofti.Manager/Pages/Configs/Update.cshtml
@model ConfigModel

@{
    ViewBag.Title = "Update Config";
    Layout = "_Layout";
}

<h2>Update Config</h2>

<form asp-controller="Configs" asp-action="Update" asp-route-configId="@Model.Id" asp-route-appId="@ViewBag.AppId" method="post">
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label asp-for="Value">Value</label>
        <input asp-for="Value" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="IsActive">Is Active</label>
        <input asp-for="IsActive" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

src/Kofti.Manager/Pages/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/Kofti.Manager/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Kofti.Manager</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Kofti.Manager</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Kofti.Manager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>